{
  "total": 5,
  "seed": "/etc/passwd",
  "output": "/opt/raid0/python3/data-car",
  "files": [
    {
      "index": 1,
      "seed": "/etc/passwd:1",
      "status": "done",
      "fullpath": "data-car/00001.car",
      "filename": "00001",
      "payloadCid": "bafykbzaceaxzkhsrttb5tqqszv6bpkt6n6v2wapp3uaxwd75k3tswrbsvfpms",
      "commpCid": "baga6ea4seaqac6wd26qwv2xcz3w4wmll3pj7dsrefrkxcjyabwdm7xooqpg4giq",
      "pieceSize": 34359738368,
      "carSize": 19463299209
    },
    {
      "index": 2,
      "seed": "/etc/passwd:2",
      "status": "done",
      "fullpath": "data-car/00002.car",
      "filename": "00002",
      "payloadCid": "bafykbzaceamljhvi7w7ew5dqf5mse6474jgvjplwlnwz7rcfxfmfi5pytueny",
      "commpCid": "baga6ea4seaqpaab4okd327vfcc6sl4wo7l4ic4qverlfc44ozbqav7xmschjmnq",
      "pieceSize": 34359738368,
      "carSize": 19429741801
    },
    {
      "index": 3,
      "seed": "/etc/passwd:3",
      "status": "done",
      "fullpath": "data-car/00003.car",
      "filename": "00003",
      "payloadCid": "bafykbzacedz6ayzxtbl356yg6b4w5fsr3xhux5m5imbkeuoz3suya2n6geeto",
      "commpCid": "baga6ea4seaqokd4gi5ecvakxbubcfvj7vkipd7yqdrib4hddxeivdutlhhrbiaa",
      "pieceSize": 34359738368,
      "carSize": 19589139489
    },
    {
      "index": 4,
      "seed": "/etc/passwd:4",
      "status": "done",
      "fullpath": "data-car/00004.car",
      "filename": "00004",
      "payloadCid": "bafykbzacednugktuf675fnwudmyfctxsl5crheoq2muleaqslyshevl6kvb74",
      "commpCid": "baga6ea4seaqnri4ict7rnr6dwr5txjf577lqijopgtx7ri4cery6frm4xzspscq",
      "pieceSize": 34359738368,
      "carSize": 19442325829
    },
    {
      "index": 5,
      "seed": "/etc/passwd:5",
      "status": "done",
      "fullpath": "data-car/00005.car",
      "filename": "00005",
      "payloadCid": "bafykbzaceaflc3q256b4vbi5c3h5nx4euwjad23ji6vervfluspdfidscgdmw",
      "commpCid": "baga6ea4seaqou4js4l3nwjj3gzvdk7sfwtl75kewoverah33nktt5d7znemqodi",
      "pieceSize": 34359738368,
      "carSize": 19362626985
    }
  ]
}